version: "3"

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - 27017:27017
    restart: always
    networks:
      - dev
  nest_server:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./:/usr/src/app
    networks:
      - dev
networks:
  dev: