version: "3"

services:<% if (MongoDB) { %>
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo/data:/data/db:rw
    networks:
      - backend
  <% } %><% if (MySQL) { %>mysql:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql/logs:/var/log/mysql:rw
      - ./db/mysql/data:/var/lib/mysql:rw
    networks:
      - backend
  <% } %><% if (redis) { %>redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - backend
  <% } %>nest_server:
    build:
      context: ./
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - mysql
      - redis
    volumes:
      - .:/usr/src/app
      - nest_node_modules:/usr/src/app/node_modules
    networks:
      - backend
networks:
  backend:
volumes:
  nest_node_modules: