version: "3"

services:<% if (MongoDB) { %>
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - 27017:27017
    restart: always
    networks:
      - dev
  <% } %><% if (MySQL) { %>mysql:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    networks:
      - dev
  <% } %><% if (redis) { %>redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dev
  <% } %>nest_server_dev:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - nest_dev_node_modules:/usr/src/app/node_modules
    networks:
      - dev
networks:
  dev:
volumes:
  nest_dev_node_modules: