version: "3"

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - 27017:27017
    restart: always
    networks:
      - dev
  nest_server_mongo_dev:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - nest_node_modules:/usr/src/app/node_modules
    networks:
      - dev
networks:
  dev:
volumes:
  nest_node_modules: